// Presentation/DemoReact/src/app/workitem/WorkItemEdit.jsx
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { useState } from "react";
import { useParams, Link } from "react-router-dom";

// Functions
import { useLoadData } from "../functions";
import { getWorkItemTypes } from "../functions";
import { getWorkItemStatuses } from "../functions";

const WorkItemEdit = () => {
    const [data = [], setData] = useState();
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState();
    const params = useParams();
    const id = params.id ? parseInt(params.id) : 0;

    const saveChanges = () => {
        alert("TODO: Save changes.");
    };

    const deleteItem = () => {
        alert("TODO: Delete item.");
    };

    // ------------------------------------------------------------
    // Load data
    // ------------------------------------------------------------

    // TODO: Swap out WebAPI URL to 'workItem/' + id
    useLoadData("/test/workItem/" + id, setIsLoading, setData, setError);

    // ------------------------------------------------------------
    // Presentation Layer
    // ------------------------------------------------------------

    return (
        <>
            <div className="container">
                <div className="row">
                    <div className="col">
                        <h1>{id == 0 ? "Add" : "Edit"} Work Item</h1>
                    </div>
                    <div className="col text-end mt-2">
                        <Link to={`/workitem/${id}`} className="btn btn-light border me-2">
                            <FontAwesomeIcon icon="fa-solid fa-x" className="me-2" /> Cancel
                        </Link>
                        <button type="submit" className="btn btn-primary" onClick={() => saveChanges()}>
                            <FontAwesomeIcon icon="fa-solid fa-save" className="me-2" /> Save
                        </button>
                    </div>
                </div>
                <div className="row data-row">
                    <div className="col-6">
                        <div className="mb-3">
                            <label htmlFor="typeId" className="form-label">
                                Title
                            </label>
                            <input id="title" type="text" className="form-control required" aria-label="Title" value={data.title ?? ""} required
                                onChange={(e) =>
                                    setData({
                                        ...data,
                                        title: e.target.value,
                                    })
                                }
                            />
                        </div>
                        <div className="mb-3">
                            <label htmlFor="typeId" className="form-label">
                                Work Item Type
                            </label>
                            <select id="typeId" className="form-select required" aria-label="Type" value={data.typeId ?? 0} required
                                onChange={(e) =>
                                    setData({
                                        ...data,
                                        typeId: e.target.value,
                                    })
                                }
                            >
                                {getWorkItemTypes().map((item) => (
                                    <option key={item.value} value={item.value}>
                                        {item.label}
                                    </option>
                                ))}
                            </select>
                        </div>
                        <div className="mb-3">
                            <label htmlFor="statusId" className="form-label">
                                Work Item Status
                            </label>
                            <select id="statusId" className="form-select required" aria-label="Status" value={data.statusId ?? 0} required
                                onChange={(e) =>
                                    setData({
                                        ...data,
                                        statusId: e.target.value,
                                    })
                                }
                            >
                                {getWorkItemStatuses().map((item) => (
                                    <option key={item.value} value={item.value}>
                                        {item.label}
                                    </option>
                                ))}
                            </select>
                        </div>
                    </div>
                    <div className="col-6">
                        <div className="mb-3">
                            <input id="subTitle" type="text" className="form-control" aria-label="Sub-Title" value={data.subTitle ?? ""}
                                onChange={(e) =>
                                    setData({
                                        ...data,
                                        subTitle: e.target.value,
                                    })
                                }
                            />
                        </div>
                        <div className="mb-3">
                            <textarea id="summary" type="text" className="form-control" aria-label="Summary" value={data.summary ?? ""} rows="3"
                                onChange={(e) =>
                                    setData({
                                        ...data,
                                        summary: e.target.value,
                                    })
                                }
                            />
                        </div>
                        <div className="mb-3">
                            <textarea id="body" type="text" className="form-control" aria-label="Body" value={data.body ?? ""} rows="10"
                                onChange={(e) =>
                                    setData({
                                        ...data,
                                        body: e.target.value,
                                    })
                                }
                            />
                        </div>
                    </div>
                </div>

                <div className={id == 0 ? "hidden" : "row"}>
                    <div className="col text-end">
                        <button
                            type="submit"
                            className="btn btn-danger"
                            onClick={() => deleteItem()}
                        >
                            <FontAwesomeIcon icon="fa-solid fa-trash" className="me-2" />{" "}
                            Delete
                        </button>
                    </div>
                </div>
            </div >
        </>
    );
};

export default WorkItemEdit;

// Presentation/DemoAngular/src/app/workitem/workitem-edit/workitem-edit.component.ts
import { Component } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { faTrash } from '@fortawesome/free-solid-svg-icons';
import { faX } from '@fortawesome/free-solid-svg-icons';
import { faSave } from '@fortawesome/free-solid-svg-icons';
import { IWorkItem } from '../../../models/workitem.model';
import { WorkItemService } from '../../../services/workitem.service';

declare var bootbox: any;

@Component({
  selector: 'demo-workitem-edit',
  templateUrl: './workitem-edit.component.html',
  styleUrls: ['./workitem-edit.component.css'],
})
export class WorkItemEditComponent {
  id: number = 0;
  workItem: any;
  faTrash = faTrash;
  faX = faX;
  faSave = faSave;

  workItemTypes = [
    { value: '0', label: 'Select...' },
    { value: '1', label: 'User Story' },
    { value: '2', label: 'Task' },
    { value: '3', label: 'Bug' },
    { value: '4', label: 'Epic' },
    { value: '5', label: 'Feature' },
  ];

  workItemStatuses = [
    { value: '0', label: 'Select...' },
    { value: '1', label: 'New' },
    { value: '2', label: 'In Planning' },
    { value: '3', label: 'In Progress' },
    { value: '4', label: 'Approved' },
    { value: '5', label: 'Rejected' },
    { value: '6', label: 'Staged' },
    { value: '7', label: 'Completed' },
    { value: '8', label: 'On Hold' },
  ];

  constructor(
    private router: Router,
    private route: ActivatedRoute,
    private workItemSvc: WorkItemService
  ) {}

  ngOnInit() {
    this.route.paramMap.subscribe((params) => {
      this.id = parseInt(params.get('id') ?? '0') ?? 0;
    });

    if (this.id === 0) {
      // Create new WorkItem
      this.workItem = {
        id: 0,
        guid: '',
        typeId: 0,
        type: '',
        statusId: 0,
        status: '',
        isActive: true,
        isDeleted: false,
        title: '',
        subTitle: '',
        summary: '',
        body: '',
      };
    } else {
      // Get WorkItem
      this.workItemSvc
        .getWorkItem(this.id)
        .subscribe(
          (workItem: IWorkItem | undefined) => (this.workItem = workItem)
        );
    }
  }

  saveWorkItem() {
    bootbox.alert('TODO: Save WorkItem');
  }

  deleteWorkItem() {
    bootbox.confirm(
      'Are you sure you want to delete this Work Item?',
      (result: boolean) => {
        if (result) {
          bootbox.alert('TODO: Delete WorkItem');
        }
      }
    );
  }
}

<div class="container">
  <div class="row">
    <div class="col">
      <h1>{{ id === 0 ? "Add" : "Edit" }} Work Item</h1>
    </div>
    <div class="col text-end mt-2">
      <button class="btn btn-light border me-2" routerLink="/workitems">
        <fa-icon [icon]="faX"></fa-icon> Cancel
      </button>
      <button type="submit" class="btn btn-primary" (click)="saveWorkItem()">
        <fa-icon [icon]="faSave"></fa-icon> Save
      </button>
    </div>
  </div>
  <form>
    <div class="row">
      <div class="col">
        <div class="mb-3">
          <label for="title" class="form-label">Title</label>
          <input
            class="form-control required"
            required
            id="title"
            name="title"
            [(ngModel)]="workItem.title"
          />
        </div>
        <div class="mb-3">
          <label for="typeId" class="form-label">WorkItem Type</label>
          <select
            class="form-select required"
            required
            aria-label="Type"
            id="typeId"
            name="typeId"
            [(ngModel)]="workItem.typeId"
          >
            <option
              *ngFor="let workItemType of workItemTypes"
              [value]="workItemType.value"
            >
              {{ workItemType.label }}
            </option>
          </select>
        </div>
        <div class="mb-3">
          <label for="satusId" class="form-label">WorkItem Status</label>
          <select
            class="form-select required"
            required
            aria-label="Status"
            id="statusId"
            name="statusId"
            [(ngModel)]="workItem.statusId"
          >
            <option
              *ngFor="let workItemStatus of workItemStatuses"
              [value]="workItemStatus.value"
            >
              {{ workItemStatus.label }}
            </option>
          </select>
        </div>
        <div class="mb-3">
          <label for="subTitle" class="form-label">Sub-Title</label>
          <input
            class="form-control required"
            required
            id="subTitle"
            name="subTitle"
            [(ngModel)]="workItem.subTitle"
          />
        </div>
        <div class="mb-3">
          <div class="form-check">
            <input
              class="form-check-input"
              type="checkbox"
              id="isActive"
              name="isActive"
              [(ngModel)]="workItem.isActive"
            />
            <label class="form-check-label" for="isActive"> Active </label>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="mb-3">
          <label for="summary" class="form-label">Summary</label>
          <textarea
            class="form-control"
            id="subTitle"
            name="subTitle"
            rows="3"
            [(ngModel)]="workItem.subTitle"
          ></textarea>
        </div>
        <div class="mb-3">
          <label for="body" class="form-label">Body</label>
          <textarea
            class="form-control"
            id="body"
            name="body"
            rows="12"
            [(ngModel)]="workItem.body"
          ></textarea>
        </div>
      </div>
    </div>
  </form>
  <div *ngIf="id != 0" class="row">
    <div class="col text-end">
      <button class="btn btn-danger" (click)="deleteWorkItem()">
        <fa-icon [icon]="faTrash"></fa-icon> Delete
      </button>
    </div>
  </div>
</div>
