// Presentation/DemoAngular/src/app/client/client-list/client-list.component.ts
import { Component } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { faAdd } from '@fortawesome/free-solid-svg-icons';
import { IClient } from '../../../models/client.model';
import { ClientService } from '../../../services/client.service';

@Component({
  selector: 'demo-client-list',
  templateUrl: './client-list.component.html',
  styleUrls: ['./client-list.component.css'],
})
export class ClientListComponent {
  clients: any;
  filter: string = '';
  faAdd = faAdd;
  headers = [
    { key: 'name', displayName: 'Name' },
    { key: 'type', displayName: 'Type' },
    { key: 'isActive', displayName: 'Active' },
    { key: 'city', displayName: 'City' },
    { key: 'region', displayName: 'Region' },
  ];
  clickableColumns = [];

  constructor(
    private router: Router,
    private route: ActivatedRoute,
    private clientSvc: ClientService,
  ) { }

  ngOnInit() {
    this.clientSvc.getClients().subscribe((clients: IClient[]) => this.clients = clients);
    this.route.paramMap.subscribe((params) => {
      this.filter = params.get('filter') ?? '';
    });
  }

  getFilteredClients(): IClient[] {
    return !this.filter
      ? this.clients
      : this.clients.filter((client: any) => client.type.toLowerCase().replace(' ', '-') === this.filter.toLowerCase())
  }

  handleRowClick(client: any) {
    this.router.navigate(['client', client.id]);
  }

  addClient() {
    console.log('TODO: Create Client');
  }
}

<div class="container">
  <div class="row mt-3">
    <div class="col">
      <h1>Client List</h1>
    </div>
    <div class="col text-end">
      <div class="btn-group border" role="group" >
        <a class="btn btn-outline-secondary" routerLink="/clients">ALL</a>
        <a class="btn btn-outline-secondary" routerLink="/clients/internal" routerLinkActive="bg-info">Internals</a>
        <a class="btn btn-outline-secondary" routerLink="/clients/external" routerLinkActive="bg-info">Externals</a>
        <a class="btn btn-outline-secondary" routerLink="/clients/lead" routerLinkActive="bg-info">Leads</a>
      </div>
    </div>
    <div class="col-1 text-end">
      <button class="btn btn-primary" routerLink="/client/add"><fa-icon [icon]="faAdd"></fa-icon> Add</button>
    </div>
  </div>
  <app-generic-table [headers]="headers" [data]="getFilteredClients()" (rowClicked)="handleRowClick($event)" [clickableColumns]="clickableColumns"></app-generic-table>
</div>

// Presentation/DemoReact/src/app/client/ClientList.jsx
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { useState } from "react";
import ClientDataGrid from "../client/ClientDataGrid"
import { useLocation, Link } from 'react-router-dom';

function ClientList() {
    const [isClientsLoading, setIsClientsLoading] = useState();
    const [clientsRecordCount, setClientsRecordCount] = useState();
    const [clientsGridRef, setClientsGridRef] = useState();
    const location = useLocation();

    const getButtonClassName = (path) => {
        var className = 'btn btn-outline-secondary';
        if (location.pathname === path) {
            className += ' bg-info';
        }
        return className;
    };

    function onClientsGridReady(params) {
        setClientsGridRef(params.api);
    }

    return (
        <>
            <div className="container">
                <div className="row">
                    <div className="col">
                        <h1>Client List</h1>
                    </div>
                    <div className="col text-end">
                        <div className="btn-group border" role="group" >
                            <Link to="/clients" className={getButtonClassName('/clients')}>ALL</Link>
                            <Link to="/clients/internal" className={getButtonClassName('/clients/internal')}>Internals</Link>
                            <Link to="/clients/external" className={getButtonClassName('/clients/external')}>Externals</Link>
                            <Link to="/clients/lead" className={getButtonClassName('/clients/lead')}>Leads</Link>
                        </div>
                    </div>
                    <div className="col-1 text-end">
                        <Link to="/client/add" className="btn btn-primary">
                            <FontAwesomeIcon icon="fa-solid fa-plus" className="me-2" /> Add
                        </Link>
                    </div>
                </div>
                <div className="data-grid">
                    <ClientDataGrid isLoading={isClientsLoading}
                        setIsLoading={setIsClientsLoading}
                        recordCount={clientsRecordCount}
                        setRecordCount={setClientsRecordCount}
                        onGridReady={onClientsGridReady} />
                </div>
            </div>
        </>

    );
}

export default ClientList;
