// Presentation/DemoAngular/src/app/client/client-edit/client-edit.component.ts
import { Component } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { faTrash } from '@fortawesome/free-solid-svg-icons';
import { faX } from '@fortawesome/free-solid-svg-icons';
import { faSave } from '@fortawesome/free-solid-svg-icons';
import { IClient } from '../../../models/client.model';
import { ClientService } from '../../../services/client.service';

declare var bootbox: any;

@Component({
  selector: 'demo-client-edit',
  templateUrl: './client-edit.component.html',
  styleUrls: ['./client-edit.component.css'],
})
export class ClientEditComponent {
  id: number = 0;
  client: any;
  faTrash = faTrash;
  faX = faX;
  faSave = faSave;

  clientTypes = [
    { value: '0', label: 'Select...' },
    { value: '1', label: 'Internal' },
    { value: '2', label: 'External' },
    { value: '3', label: 'Lead' },
  ];

  regions = [
    { value: 'AL', label: 'Alabama[ngValue]=' },
    { value: 'AB', label: 'Alberta[ngValue]=' },
    { value: 'BC', label: 'British Columbia[ngValue]=' },
    { value: 'MB', label: 'Manitoba[ngValue]=' },
    { value: 'NB', label: 'New Brunswick[ngValue]=' },
    { value: 'NL', label: 'Newfoundland and Labrador[ngValue]=' },
    { value: 'NS', label: 'Nova Scotia[ngValue]=' },
    { value: 'NT', label: 'Northwest Territories[ngValue]=' },
    { value: 'NU', label: 'Nunavut[ngValue]=' },
    { value: 'ON', label: 'Ontario[ngValue]=' },
    { value: 'PE', label: 'Prince Edward Island[ngValue]=' },
    { value: 'QC', label: 'Quebec[ngValue]=' },
    { value: 'SK', label: 'Saskatchewan[ngValue]=' },
    { value: 'YT', label: 'Yukon[ngValue]=' },
    { value: 'ENG', label: 'England[ngValue]=' },
    { value: 'NIR', label: 'Northern Ireland[ngValue]=' },
    { value: 'SCT', label: 'Scotland[ngValue]=' },
    { value: 'WLS', label: 'Wales[ngValue]=' },
    { value: 'IOM', label: 'Isle of Man[ngValue]=' },
    { value: 'GIB', label: 'Gibraltar[ngValue]=' },
    { value: 'GGY', label: 'Guernsey[ngValue]=' },
    { value: 'JEY', label: 'Jersey[ngValue]=' },
    { value: 'AK', label: 'Alaska[ngValue]=' },
    { value: 'AZ', label: 'Arizona[ngValue]=' },
    { value: 'AR', label: 'Arkansas[ngValue]=' },
    { value: 'CA', label: 'California[ngValue]=' },
    { value: 'CO', label: 'Colorado[ngValue]=' },
    { value: 'CT', label: 'Connecticut[ngValue]=' },
    { value: 'DE', label: 'Delaware[ngValue]=' },
    { value: 'FL', label: 'Florida[ngValue]=' },
    { value: 'GA', label: 'Georgia[ngValue]=' },
    { value: 'HI', label: 'Hawaii[ngValue]=' },
    { value: 'ID', label: 'Idaho[ngValue]=' },
    { value: 'IL', label: 'Illinois[ngValue]=' },
    { value: 'IN', label: 'Indiana[ngValue]=' },
    { value: 'IA', label: 'Iowa[ngValue]=' },
    { value: 'KS', label: 'Kansas[ngValue]=' },
    { value: 'KY', label: 'Kentucky[ngValue]=' },
    { value: 'LA', label: 'Louisiana[ngValue]=' },
    { value: 'ME', label: 'Maine[ngValue]=' },
    { value: 'MD', label: 'Maryland[ngValue]=' },
    { value: 'MA', label: 'Massachusetts[ngValue]=' },
    { value: 'MI', label: 'Michigan[ngValue]=' },
    { value: 'MN', label: 'Minnesota[ngValue]=' },
    { value: 'MS', label: 'Mississippi[ngValue]=' },
    { value: 'MO', label: 'Missouri[ngValue]=' },
    { value: 'MT', label: 'Montana[ngValue]=' },
    { value: 'NE', label: 'Nebraska[ngValue]=' },
    { value: 'NV', label: 'Nevada[ngValue]=' },
    { value: 'NH', label: 'New Hampshire[ngValue]=' },
    { value: 'NJ', label: 'New Jersey[ngValue]=' },
    { value: 'NM', label: 'New Mexico[ngValue]=' },
    { value: 'NY', label: 'New York[ngValue]=' },
    { value: 'NC', label: 'North Carolina[ngValue]=' },
    { value: 'ND', label: 'North Dakota[ngValue]=' },
    { value: 'OH', label: 'Ohio[ngValue]=' },
    { value: 'OK', label: 'Oklahoma[ngValue]=' },
    { value: 'OR', label: 'Oregon[ngValue]=' },
    { value: 'PA', label: 'Pennsylvania[ngValue]=' },
    { value: 'RI', label: 'Rhode Island[ngValue]=' },
    { value: 'SC', label: 'South Carolina[ngValue]=' },
    { value: 'SD', label: 'South Dakota[ngValue]=' },
    { value: 'TN', label: 'Tennessee[ngValue]=' },
    { value: 'TX', label: 'Texas[ngValue]=' },
    { value: 'UT', label: 'Utah[ngValue]=' },
    { value: 'VT', label: 'Vermont[ngValue]=' },
    { value: 'VA', label: 'Virginia[ngValue]=' },
    { value: 'WA', label: 'Washington[ngValue]=' },
    { value: 'WV', label: 'West Virginia[ngValue]=' },
    { value: 'WI', label: 'Wisconsin[ngValue]=' },
    { value: 'WY', label: 'Wyoming[ngValue]=' },
  ];

  countries = [
    { value: '', label: 'Select...' },
    { value: 'Canada', label: 'Canada' },
    { value: 'UK', label: 'United Kingdom' },
    { value: 'USA', label: 'United States of America' },
  ];

  constructor(
    private router: Router,
    private route: ActivatedRoute,
    private clientSvc: ClientService
  ) { }

  ngOnInit() {
    this.route.paramMap.subscribe((params) => {
      this.id = parseInt(params.get('id') ?? '0') ?? 0;
    });

    if (this.id === 0) {
      // Create new client
      this.client = {
        id: 0,
        guid: '',
        typeId: 0,
        type: '',
        isActive: true,
        isDeleted: false,
        name: '',
        addressLine1: '',
        addressLine2: '',
        city: '',
        region: '',
        postalCode: '',
        country: '',
        phoneNumber: '',
        url: '',
      };
    } else {
      // Get client
      this.clientSvc
        .getClient(this.id)
        .subscribe((client: IClient | undefined) => (this.client = client));

    }
  }

  saveClient() {
    bootbox.alert('TODO: Save User');
    // this.client = this.clientSvc.saveClient(this.client);
  }

  deleteClient() {
    bootbox.confirm(
      'Are you sure you want to delete this Client?',
      (result: boolean) => {
        if (result) {
          bootbox.alert('TODO: Delete Client');
        }
      }
    );
  }
}

<div class="container">
  <div class="row">
    <div class="col">
      <h1>{{ id === 0 ? "Add" : "Edit" }} Client</h1>
    </div>
    <div class="col text-end mt-2">
      <button class="btn btn-light border me-2" routerLink="/clients">
        <fa-icon [icon]="faX"></fa-icon> Cancel
      </button>
      <button type="submit" class="btn btn-primary" (click)="saveClient()">
        <fa-icon [icon]="faSave"></fa-icon> Save
      </button>
    </div>
  </div>
  <form>
    <div class="row mb-2">
      <div class="col">
        <div class="mb-3">
          <label for="name" class="form-label">Company Name</label>
          <input
            type="text"
            class="form-control required"
            required
            id="name"
            name="name"
            [(ngModel)]="client.name"
            #name="ngModel"
          />
        </div>
        <div class="mb-3">
          <label for="typeId" class="form-label">Client Type</label>
          <select
            class="form-select required"
            required
            aria-label="Type"
            id="typeId"
            name="typeId"
            [(ngModel)]="client.TypeId"
          >
            <option
              *ngFor="let clientType of clientTypes"
              [value]="client.value"
            >
              {{ clientType.label }}
            </option>
          </select>
        </div>
        <div class="mb-3">
          <label for="phoneNumber" class="form-label">Phone Number</label>
          <input
            type="tel"
            class="form-control"
            id="phoneNumber"
            name="phoneNumber"
            [(ngModel)]="client.phoneNumber"
          />
        </div>
        <div class="mb-3">
          <label for="url" class="form-label">URL / Website</label>
          <input
            type="url"
            class="form-control"
            id="url"
            name="url"
            [(ngModel)]="client.url"
          />
        </div>
        <div class="mb-3">
          <div class="form-check">
            <input
              type="checkbox"
              class="form-check-input"
              id="isActive"
              name="isActive"
              [(ngModel)]="client.isActive"
            />
            <label class="form-check-label" for="isActive"> Active </label>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card">
          <div class="card-header">Address</div>
          <div class="card-body">
            <div class="mb-3">
              <label for="address1" class="form-label">Address</label>
              <input
                type="text"
                class="form-control mb-3"
                id="addressLine1"
                name="addressLine1"
                placeholder="Line 1..."
                [(ngModel)]="client.addressLine1"
              />
              <input
                type="text"
                class="form-control"
                id="addressLine2"
                name="addressLine2"
                placeholder="Line 2..."
                [(ngModel)]="client.addressLine2"
              />
            </div>
            <div class="mb-3">
              <label for="city" class="form-label">City</label>
              <input
                type="text"
                class="form-control"
                id="city"
                name="city"
                [(ngModel)]="client.city"
              />
            </div>
            <div class="row">
              <div class="col">
                <div class="mb-3">
                  <label for="region" class="form-label">Region</label>
                  <input
                    type="text"
                    class="form-control"
                    list="datalistOptions"
                    id="region"
                    name="region"
                    placeholder="Type to search..."
                    [(ngModel)]="client.region"
                  />
                  <datalist id="region">
                    <option
                      *ngFor="let region of regions"
                      [value]="region.value"
                    >
                      {{ region.label }}
                    </option>
                  </datalist>
                </div>
              </div>
              <div class="col">
                <div class="mb-3">
                  <label for="postalCode" class="form-label">Postal Code</label>
                  <input
                    type="text"
                    class="form-control"
                    id="postalCode"
                    name="postalCode"
                    [(ngModel)]="client.postalCode"
                  />
                </div>
              </div>
            </div>
            <div class="mb-3">
              <label for="country" class="form-label">Country</label>
              <select
                class="form-select"
                aria-label="Country"
                id="country"
                name="country"
                [(ngModel)]="client.country"
              >
                <option
                  *ngFor="let country of countries"
                  [value]="country.value"
                >
                  {{ country.label }}
                </option>
              </select>
            </div>
          </div>
        </div>
      </div>
    </div>
  </form>
  <div *ngIf="id != 0" class="row">
    <div class="col text-end">
      <button class="btn btn-danger" (click)="deleteClient()">
        <fa-icon [icon]="faTrash"></fa-icon> Delete
      </button>
    </div>
  </div>
</div>

// Presentation/DemoReact/src/app/client/ClientEdit.jsx
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { useState } from "react";
import { useParams, Link } from 'react-router-dom';

// Functions
import { useLoadData } from '../functions';
import { getClientTypes } from '../functions';
import { getRegions } from '../functions';
import { getCountries } from '../functions';

const ClientEdit = () => {
    const [data = {}, setData] = useState();
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState();
    const params = useParams();
    const id = params.id ? parseInt(params.id) : 0;

    const saveChanges = () => {
        alert("TODO: Save changes.");
    }

    const deleteItem = () => {
        alert("TODO: Delete item.");
    }

    // ------------------------------------------------------------
    // Load data
    // ------------------------------------------------------------

    useLoadData('/test/client/' + id, setIsLoading, setData, setError);

    // ------------------------------------------------------------
    // Presentation Layer
    // ------------------------------------------------------------

    return (
        <>
            <div className="container">
                <div className="row">
                    <div className="col">
                        <h1>{id == 0 ? "Add" : "Edit"} Client</h1>
                    </div>
                    <div className="col text-end mt-2">
                        <Link to={`/client/${id}`} className="btn btn-light border me-2">
                            <FontAwesomeIcon icon="fa-solid fa-x" className="me-2" /> Cancel
                        </Link>
                        <button type="submit" className="btn btn-primary" onClick={() => saveChanges()}>
                            <FontAwesomeIcon icon="fa-solid fa-save" className="me-2" /> Save
                        </button>
                    </div>
                </div>
                <form>
                    <div className="row mb-2">
                        <div className="col">
                            <div className="mb-3">
                                <label htmlFor="name" className="form-label">Company Name</label>
                                <input id="name" type="text" className="form-control required" aria-label="Name" value={data.name ?? ''} required
                                    onChange={(e) =>
                                        setData({
                                            ...data,
                                            name: e.target.value,
                                        })
                                    }
                                />
                            </div>
                            <div className="mb-3">
                                <label htmlFor="typeId" className="form-label">Client Type</label>
                                <select id="typeId" className="form-select required" aria-label="Type" value={data.typeId ?? 0} required
                                    onChange={(e) =>
                                        setData({
                                            ...data,
                                            typeId: e.target.value,
                                        })
                                    }
                                >
                                    {getClientTypes().map(item => (
                                        <option key={item.value} value={item.value}>{item.label}</option>
                                    ))}
                                </select>
                            </div>
                            <div className="mb-3">
                                <label htmlFor="phoneNumber" className="form-label">Phone Number</label>
                                <input id="phoneNumber" type="tel" className="form-control" aria-label="Phone Number" value={data.phoneNumber ?? ''}
                                    onChange={(e) =>
                                        setData({
                                            ...data,
                                            phoneNumber: e.target.value,
                                        })
                                    }
                                />
                            </div>
                            <div className="mb-3">
                                <label htmlFor="url" className="form-label">URL / Website</label>
                                <input id="url" type="url" className="form-control" aria-label="URL" value={data.url ?? ''}
                                    onChange={(e) =>
                                        setData({
                                            ...data,
                                            url: e.target.value,
                                        })
                                    }
                                />
                            </div>
                            <div className="mb-3">
                                <input id="isActive" type="checkbox" className="form-check-input me-2" aria-label="Active" checked={data.isActive ?? false}
                                    onChange={(e) =>
                                        setData({
                                            ...data,
                                            isActive: e.target.checked,
                                        })
                                    }
                                />
                                <label htmlFor="isActive" className="form-label">Active</label>
                            </div>
                        </div>
                        <div className="col">
                            <div className="card">
                                <div className="card-header">Address</div>
                                <div className="card-body">
                                    <div className="mb-3">
                                        <div className="mb-3">
                                            <label htmlFor="addressLine1" className="form-label">Address</label>
                                            <input id="addressLine1" type="text" className="form-control mb-2" aria-label="Address Line 1" value={data.addressLine1 ?? ''} placeholder="Line 1..."
                                                onChange={(e) =>
                                                    setData({
                                                        ...data,
                                                        addressLine1: e.target.value,
                                                    })
                                                }
                                            />
                                            <input id="addressLine2" type="text" className="form-control mb-3" aria-label="Address Line 2" value={data.addressLine2 ?? ''} placeholder="Line 2..."
                                                onChange={(e) =>
                                                    setData({
                                                        ...data,
                                                        addressLine2: e.target.value,
                                                    })
                                                }
                                            />
                                            <div className="mb-3">
                                                <label htmlFor="city" className="form-label">City</label>
                                                <input id="city" type="text" className="form-control mt-2" aria-label="city" value={data.city ?? ''} placeholder="City..."
                                                    onChange={(e) =>
                                                        setData({
                                                            ...data,
                                                            city: e.target.value,
                                                        })
                                                    }
                                                />
                                            </div>
                                        </div>
                                        <div className="row">
                                            <div className="col">
                                                <div className="mb-3">
                                                    <label htmlFor="region" className="form-label">Region</label>
                                                    <input id="region" type="text" list="regionList" className="form-control mb-2" aria-label="Region" value={data.region ?? ''} placeholder="Type to search..."
                                                        onChange={(e) =>
                                                            setData({
                                                                ...data,
                                                                region: e.target.value,
                                                            })
                                                        }
                                                    />
                                                    <datalist id="regionList">
                                                        {getRegions().map(item => (
                                                            <option key={item.value} value={item.value}>{item.label}</option>
                                                        ))}
                                                    </datalist>
                                                </div>
                                            </div>
                                            <div className="col">
                                                <div className="mb-3">
                                                    <label htmlFor="postalCode" className="form-label">Postal Code</label>
                                                    <input id="postalCode" type="text" className="form-control mb-2" aria-label="Postal Code" value={data.postalCode ?? ''}
                                                        onChange={(e) =>
                                                            setData({
                                                                ...data,
                                                                postalCode: e.target.value,
                                                            })
                                                        }
                                                    />
                                                </div>
                                            </div>
                                        </div>
                                        <div className="mb-3">
                                            <label htmlFor="country" className="form-label">Country</label>
                                            <select id="country" className="form-select" aria-label="Country" value={data.country ?? ''}
                                                onChange={(e) =>
                                                    setData({
                                                        ...data,
                                                        country: e.target.value,
                                                    })
                                                }
                                            >
                                                {getCountries().map(item => (
                                                    <option key={item.value} value={item.value}>{item.label}</option>
                                                ))}
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form >
                <div className={id == 0 ? 'hidden' : 'row'}>
                    <div className="col text-end">
                        <button type="submit" className="btn btn-danger" onClick={() => deleteItem()}>
                            <FontAwesomeIcon icon="fa-solid fa-trash" className="me-2" /> Delete
                        </button>
                    </div>
                </div>
            </div >
        </>
    );
}

export default ClientEdit;
