// Presentation/DemoAngular/src/app/workitem/workitem-detail/workitem-detail.component.ts
import { Component } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { faPencil } from '@fortawesome/free-solid-svg-icons';
import { IWorkItem } from '../../../models/workitem.model';
import { WorkItemService } from '../../../services/workitem.service';

declare var bootbox: any;

@Component({
  selector: 'demo-workitem-detail',
  templateUrl: './workitem-detail.component.html',
  styleUrls: ['./workitem-detail.component.css']
})
export class WorkItemDetailComponent {
  id: number = 0;
  workItem: any;
  faPencil = faPencil;

  constructor(
    private router: Router,
    private route: ActivatedRoute,
    private workItemSvc: WorkItemService
  ) { }

  ngOnInit() {
    this.route.paramMap.subscribe((params) => {
      this.id = parseInt(params.get('id') ?? '0') ?? 0;
    });
    this.workItemSvc.getWorkItem(this.id).subscribe((workItem: IWorkItem | undefined) => this.workItem = workItem);
  }

  deleteWorkItem() {
    bootbox.confirm('Are you sure you want to delete this WorkItem?', (result: boolean) => {
      if (result) {
        bootbox.alert('TODO: Delete WorkItem');
      }
    });
  }
}

<div class="container">
  <div class="row">
    <div class="col">
      <h1>WorkItem Detail</h1>
    </div>
    <div class="col text-end mt-2">
      <button class="btn btn-primary" routerLink="/workitem/edit/{{ workItem.id }}"><fa-icon [icon]="faPencil"></fa-icon> Edit</button>
    </div>
  </div>
  <div class="container data">
    <div class="row data-row">
      <div class="col-2 col-key">
        Id
      </div>
      <div class="col-10 col-value">
        {{ workItem.id }}
      </div>
    </div>
    <div class="row data-row">
      <div class="col-2 col-key">
        Guid
      </div>
      <div class="col-10 col-value">
        {{ workItem.guid }}
      </div>
    </div>
    <div class="row data-row">
      <div class="col-2 col-key">
        TypeId
      </div>
      <div class="col-10 col-value">
        {{ workItem.typeId }}
      </div>
    </div>
    <div class="row data-row">
      <div class="col-2 col-key">
        Type
      </div>
      <div class="col-10 col-value">
        {{ workItem.type }}
      </div>
    </div>
    <div class="row data-row">
      <div class="col-2 col-key">
        StatusId
      </div>
      <div class="col-10 col-value">
        {{ workItem.statusId }}
      </div>
    </div>
    <div class="row data-row">
      <div class="col-2 col-key">
        Status
      </div>
      <div class="col-10 col-value">
        {{ workItem.status }}
      </div>
    </div>
    <div class="row data-row">
      <div class="col-2 col-key">
        Title
      </div>
      <div class="col-10 col-value">
        <div>{{ workItem.title }}</div>
      </div>
    </div>
    <div class="row data-row">
      <div class="col-2 col-key">
        Sub-Title
      </div>
      <div class="col-10 col-value">
        <div>{{ workItem.subTitle }}</div>
      </div>
    </div>
    <div class="row data-row">
      <div class="col-2 col-key">
        Summary
      </div>
      <div class="col-10 col-value">
        <div>{{ workItem.summary }}</div>
      </div>
    </div>
    <div class="row data-row">
      <div class="col-2 col-key">
        Body
      </div>
      <div class="col-10 col-value">
        <div>{{ workItem.body }}</div>
      </div>
    </div>
  </div>
</div>

// Presentation/DemoReact/src/app/workitem/WorkItemDetail.jsx
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { useState } from "react";
import { useParams, Link } from 'react-router-dom';

// Functions
import { useLoadData } from '../functions';

const WorkItemDetail = () => {
    const [data = [], setData] = useState();
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState();
    const params = useParams();
    const id = parseInt(params.id);

    // ------------------------------------------------------------
    // Load data
    // ------------------------------------------------------------

    // TODO: Swap out WebAPI URL to 'workItem/' + id
    useLoadData('/test/workItem/' + id, setIsLoading, setData, setError);

    // ------------------------------------------------------------
    // Presentation Layer
    // ------------------------------------------------------------

    return (
        <>
            <div className="container">
                <div className="row">
                    <div className="col">
                        <h1>View Work Item</h1>
                    </div>
                    <div className="col text-end mt-2">
                        <Link to="/workitems" className="btn btn-light border me-2">
                            <FontAwesomeIcon icon="fa-solid fa-x" className="me-2" /> Cancel
                        </Link>
                        <Link to={`/workitem/${id}/edit`} className="btn btn-primary">
                            <FontAwesomeIcon icon="fa-solid fa-pencil" className="me-2" /> Edit
                        </Link>
                    </div>
                </div>
                <div className="container data">
                    <div className="row data-row">
                        <div className="col-2 col-key">
                            Id
                        </div>
                        <div className="col-10 col-value">
                            {id}
                        </div>
                    </div>
                    <div className="row data-row">
                        <div className="col-2 col-key">
                            Guid
                        </div>
                        <div className="col-10 col-value">
                            {data.guid}
                        </div>
                    </div>
                    <div className="row data-row">
                        <div className="col-2 col-key">
                            TypeId
                        </div>
                        <div className="col-10 col-value">
                            {data.typeId}
                        </div>
                    </div>
                    <div className="row data-row">
                        <div className="col-2 col-key">
                            Type
                        </div>
                        <div className="col-10 col-value">
                            {data.type}
                        </div>
                    </div>
                    <div className="row data-row">
                        <div className="col-2 col-key">
                            StatusId
                        </div>
                        <div className="col-10 col-value">
                            {data.statusId}
                        </div>
                    </div>
                    <div className="row data-row">
                        <div className="col-2 col-key">
                            Status
                        </div>
                        <div className="col-10 col-value">
                            {data.status}
                        </div>
                    </div>
                    <div className="row data-row">
                        <div className="col-2 col-key">
                            Title
                        </div>
                        <div className="col-10 col-value">
                            {data.title}
                        </div>
                    </div>
                    <div className="row data-row">
                        <div className="col-2 col-key">
                            Sub-Title
                        </div>
                        <div className="col-10 col-value">
                            {data.subTitle}
                        </div>
                    </div>
                    <div className="row data-row">
                        <div className="col-2 col-key">
                            Summary
                        </div>
                        <div className="col-10 col-value">
                            {data.summary}
                        </div>
                    </div>
                    <div className="row data-row">
                        <div className="col-2 col-key">
                            Body
                        </div>
                        <div className="col-10 col-value">
                            {data.body}
                        </div>
                    </div>
                </div>
            </div >
        </>
    );
}

export default WorkItemDetail;
