// Presentation/DemoAngular/src/app/workitem/workitem-list/workitem-list.component.ts
import { Component } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { faAdd } from '@fortawesome/free-solid-svg-icons';
import { IWorkItem } from '../../../models/workitem.model';
import { WorkItemService } from '../../../services/workitem.service';

@Component({
  selector: 'demo-workitem-list',
  templateUrl: './workitem-list.component.html',
  styleUrls: ['./workitem-list.component.css']
})
export class WorkItemListComponent {
  workItems: any;
  filter: string = '';
  faAdd = faAdd;
  headers = [
    { key: 'title', displayName: 'Title' },
    { key: 'clientName', displayName: 'Client' },
    { key: 'type', displayName: 'Type' },
    { key: 'status', displayName: 'Status' },
    { key: 'isActive', displayName: 'Active' },
    { key: 'subTitle', displayName: 'Sub-Title' },
  ];
  clickableColumns = ['title'];

  constructor(
    private router: Router,
    private route: ActivatedRoute,
    private workItemSvc: WorkItemService
  ) { }

  ngOnInit() {
    this.workItemSvc.getWorkItems().subscribe((workItems: IWorkItem[]) => this.workItems = workItems);
    this.route.paramMap.subscribe((params) => {
      this.filter = params.get('filter') ?? '';
    });
  }

  getFilteredWorkItems(): IWorkItem[] {
    return !this.filter
      ? this.workItems
      : this.workItems.filter((workItem: any) => workItem.type.toLowerCase().replace(' ', '-') === this.filter.toLowerCase());
  }

  handleRowClick(workItem: any) {
    this.router.navigate(['workitem', workItem.id]);
  }

  addWorkItem() {
    alert('TODO: Create WorkItem');
  }
}

<div class="container">
  <div class="row mt-3">
    <div class="col">
      <h1>Work Item List</h1>
    </div>
    <div class="col text-end">
      <div class="btn-group border" role="group">
        <a class="btn btn-outline-secondary" routerLink="/workitems">ALL</a>
        <a class="btn btn-outline-secondary" routerLink="/workitems/user-story" routerLinkActive="btn-info">User Stories</a>
        <a class="btn btn-outline-secondary" routerLink="/workitems/task" routerLinkActive="btn-info">Tasks</a>
        <a class="btn btn-outline-secondary" routerLink="/workitems/bug" routerLinkActive="btn-info">Bugs</a>
        <a class="btn btn-outline-secondary" routerLink="/workitems/epic" routerLinkActive="btn-info">Epics</a>
        <a class="btn btn-outline-secondary" routerLink="/workitems/feature" routerLinkActive="btn-info">Features</a>
      </div>
    </div>
    <div class="col-1 text-end">
      <button class="btn btn-primary" routerLink="/workitem/add"><fa-icon [icon]="faAdd"></fa-icon> Add</button>
    </div>
  </div>
  <app-generic-table [headers]="headers" [data]="getFilteredWorkItems()" (rowClicked)="handleRowClick($event)" [clickableColumns]="clickableColumns"></app-generic-table>
</div>

// Presentation/DemoReact/src/app/workitem/WorkItemList.jsx
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { useState } from "react";
import WorkItemDataGrid from "../workItem/WorkItemDataGrid"
import { useLocation, Link } from 'react-router-dom';

function WorkItemList() {
    const [isWorkItemsLoading, setIsWorkItemsLoading] = useState();
    const [workItemsRecordCount, setWorkItemsRecordCount] = useState();
    const [workItemsGridRef, setWorkItemsGridRef] = useState();
    const location = useLocation();

    const getButtonClassName = (path) => {
        var className = 'btn btn-outline-secondary';
        if (location.pathname === path) {
            className += ' bg-info';
        }
        return className;
    };

    function onWorkItemsGridReady(params) {
        setWorkItemsGridRef(params.api);
    }

    return (
        <>
            <div className="container">
                <div className="row">
                    <div className="col">
                        <h1>Work Item List</h1>
                    </div>
                    <div className="col text-end">
                        <div className="btn-group border" role="group" >
                            <Link to="/workitems" className={getButtonClassName('/workitems')}>ALL</Link>
                            <Link to="/workitems/user-story" className={getButtonClassName('/workitems/user-story')}>User Stories</Link>
                            <Link to="/workitems/task" className={getButtonClassName('/workitems/task')}>Tasks</Link>
                            <Link to="/workitems/bug" className={getButtonClassName('/workitems/bug')}>Bugs</Link>
                            <Link to="/workitems/epic" className={getButtonClassName('/workitems/epic')}>Epic</Link>
                            <Link to="/workitems/feature" className={getButtonClassName('/workitems/feature')}>Features</Link>
                        </div>
                    </div>
                    <div className="col-1 text-end">
                        <Link to="/workitem/add" className="btn btn-primary">
                            <FontAwesomeIcon icon="fa-solid fa-plus" className="me-2" /> Add
                        </Link>
                    </div>
                </div>
                <div className="data-grid">
                    <WorkItemDataGrid isLoading={isWorkItemsLoading}
                        setIsLoading={setIsWorkItemsLoading}
                        recordCount={workItemsRecordCount}
                        setRecordCount={setWorkItemsRecordCount}
                        onGridReady={onWorkItemsGridReady} />
                </div>
            </div>
        </>

    );
}

export default WorkItemList;
