// Presentation/DemoReact/src/components/Login.jsx
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import Spinner from 'react-bootstrap/Spinner';
import { useAuth } from "../utils/AuthProvider";

const Login = () => {
    const navigate = useNavigate();
    const { login } = useAuth();
    const [username, setUsername] = useState('');
    const [password, setPassword] = useState('');
    const [rememberMe, setRememberMe] = useState('');
    const [isAuthenticating, setIsAuthenticating] = useState(false);
    const [authenticationFailed, setAuthenticationFailed] = useState(false);

    const handleSubmit = async (event) => {
        event.preventDefault();

        setIsAuthenticating(true);
        setAuthenticationFailed(false);

        const isAuthenticated = login(username, password, rememberMe);
        if (isAuthenticated) {
            navigate('/');
        } else {
            setIsAuthenticating(false);
            setAuthenticationFailed(true);
        }
    };

    return (
        <form onSubmit={handleSubmit}>
            <div className="row">
                <div className="col-2 offset-md-5">
                    <h1 className="text-center">
                        <FontAwesomeIcon icon="fa-brands fa-react" className="me-2" />
                        DemoReact
                    </h1>
                    <input id="username" type="text" className="form-control required mb-2" required
                        aria-label="Username" placeholder="Username"
                        value={username}
                        onChange={(e) => setUsername(e.target.value)} />
                    <input id="password" type="password" className="form-control required mb-2" required
                        aria-label="Password" placeholder="Password"
                        value={password}
                        onChange={(e) => setPassword(e.target.value)} />
                    <div className="row ">
                        <div className="col-6 pt-1">
                            <input id="rememberMe" type="checkbox" className="form-check-input me-2" aria-label="Remember Me"
                                value={rememberMe}
                                onChange={(e) => setRememberMe(e.target.checked)} />
                            <label htmlFor="isActive" className="form-label">Remember Me</label>
                        </div>
                        <div className="col-6 text-end">
                            <button type="submit" className="btn btn-primary">
                                <FontAwesomeIcon icon="fa-solid fa-sign-in" className="me-2" />
                                Login
                            </button>
                        </div>
                    </div>
                    {isAuthenticating &&
                        <div className="row">
                            <div className="col text-secondary">
                                <Spinner size="sm" animation="border" role="status" /> Authenticating...
                            </div>
                        </div>}
                    {authenticationFailed &&
                        <div className="alert alert-danger mt-2" role="alert">
                            <FontAwesomeIcon icon="fa-solid fa-exclamation-triangle" className="me-2" />
                            Invalid username or password!
                        </div>}
                </div>
            </div>
        </form>
    );
}

export default Login;

// Presentation/DemoAngular/src/app/login/login.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { faAngular } from '@fortawesome/free-brands-svg-icons';
import { faSignIn, faSpinner, faTriangleExclamation } from '@fortawesome/free-solid-svg-icons';

declare var bootbox: any;

@Component({
  selector: 'demo-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
})
export class LoginComponent {
  faAngular = faAngular;
  faSignIn = faSignIn;
  faSpinner = faSpinner;
  faTriangleExclamation = faTriangleExclamation;

  username = '';
  password = '';
  rememberMe = false;
  authenticating = false;
  authenticationFailed = false;

  constructor(private authService: AuthService, private router: Router) { }

  onSubmit() {
    this.authenticating = true;
    this.authenticationFailed = false;
    this.authService.login(this.username, this.password, this.rememberMe).subscribe((isAuthenticated: boolean) => {
      this.authenticating = false;
      if (isAuthenticated) {
        this.authenticationFailed = false;
        this.router.navigate(['/home']);
      }
      else {
        this.authenticationFailed = true;
      }
    });
  }
}

<form class="mt-4" (ngSubmit)="onSubmit()">
  <div class="row">
    <div class="col-2 offset-md-5">
      <h1 class="text-center">
        <fa-icon [icon]="faAngular"></fa-icon>
        DemoAngular
      </h1>
      <input type="text"
             class="form-control required mb-2"
             required
             id="username"
             name="username"
             aria-label="Username"
             placeholder="Username"
             [(ngModel)]="username" />
      <input type="password"
             class="form-control required mb-2"
             required
             id="password"
             name="password"
             aria-label="Password"
             placeholder="Password"
             [(ngModel)]="password" />
      <div class="row ">
        <div class="col-6 pt-1">
          <input type="checkbox"
                 class="form-check-input me-2"
                 id="rememberMe"
                 name="rememberMe"
                 aria-label="Remember Me"
                 [(ngModel)]="rememberMe" />
          <label htmlFor="isActive" class="form-label">Remember Me</label>
        </div>
        <div class="col-6 text-end">
          <button type="submit" class="btn btn-primary">
            <fa-icon [icon]="faSignIn"></fa-icon>
            Login
          </button>
        </div>
      </div>
      <div *ngIf="authenticating" class="row">
        <div class="col text-secondary">
          <fa-icon [icon]="faSpinner" [spin]="authenticating"></fa-icon> Authenticating...
        </div>
      </div>
      <div *ngIf="authenticationFailed" class="alert alert-danger mt-2" role="alert">
        <fa-icon [icon]="faTriangleExclamation" class="me-2"></fa-icon>
        Invalid username or password!
      </div>
    </div>
  </div>
</form>
