// Presentation/DemoReact/src/components/AccessDenied.jsx
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { useParams } from 'react-router-dom';

const AccessDenied = () => {
    const params = useParams();
    const page = params.page;

    return (
        <div className="error">
            <h1>
                <FontAwesomeIcon icon="fa-solid fa-lock" className="me-2" />
                Access Denied
            </h1>
            <p>Sorry, but you don't have permission to access this page.</p>
            <code>{page}</code>
        </div>
    );
}

export default AccessDenied;

// Presentation/DemoAngular/src/app/access-denied/access-denied.component.ts
import { Component } from '@angular/core';
import { faLock } from '@fortawesome/free-solid-svg-icons';

@Component({
  selector: 'demo-access-denied',
  templateUrl: './access-denied.component.html',
  styleUrls: ['./access-denied.component.css']
})
export class AccessDeniedComponent {
  faLock = faLock;
  page = '';
}

<div class="container error mt-4">
  <h1>
    <fa-icon [icon]="faLock" class="me-2"></fa-icon>
    Access Denied
  </h1>
  <p>Sorry, but you don't have permission to access this page.</p>
  <code>{{ page }}</code>
</div>
